### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [dhowden/gap-tmbundle#1]
We would like to use your lexer at github/linguist to highlight GAP code on GitHub but I don't know what licensing terms you're distributing it under.
Any chance you could pick one from here: http://choosealicense.com?

**Comment by pchaigno** [comment]
@dhowden Did you get a chance to look into this?

**Comment by dhowden** [comment]
I've added a README with some basic license terms.  Let me know if it isn't sufficient.

**Comment by pchaigno** [comment]
Thanks!

**Comment by pchaigno** [comment]
@dhowden Your grammar is now used to highlight GAP code on GitHub (files and code snippets in Markdown)! (See github/linguist#2089 for more information.)
